#!/usr/bin/env python3
"""Export Typst diagrams to SVG for the website.

Stdlib only. Extracts the #diagram / #lq.diagram call from each known
séance source (balanced parens, same technique as build_site.py), wraps
it in a page-auto document importing /template.typ, and compiles it with
``typst compile --root . --format svg`` to public/assets/figs/<stem>.svg.

Wrappers live in .build/figs/ (gitignored, never the repo), so a séance
edit is picked up on the next build with no manual wrapper sync. The
stem map (filenames, alt texts, captions) stays the single source of
truth in scripts/build_site.py:FIGURE_SVGS and is imported here.

Usage:
    python3 scripts/export_figures.py
    python3 scripts/export_figures.py --outdir public/assets/figs --workdir .build/figs
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from build_site import FIGURE_SVGS  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SEANCES_DIR = ROOT / "seances"

# First match wins; fletcher and lilaq diagram calls both end here.
DIAGRAM_RES = (
    re.compile(r"#diagram\s*\("),
    re.compile(r"#lq\.diagram\s*\("),
)

WRAPPER_TEMPLATE = """\
// Generated by scripts/export_figures.py — do not edit.
// Source: {source}
#import "/template.typ": *

#set page(width: auto, height: auto, margin: 8pt)

#align(center)[
{diagram}
]
"""


def extract_diagram(source: Path) -> str:
    """Return the first #diagram(...) / #lq.diagram(...) call, parens balanced."""
    text = source.read_text(encoding="utf-8")
    for rx in DIAGRAM_RES:
        m = rx.search(text)
        if not m:
            continue
        open_idx = text.index("(", m.start())
        depth = 0
        for i in range(open_idx, len(text)):
            if text[i] == "(":
                depth += 1
            elif text[i] == ")":
                depth -= 1
                if depth == 0:
                    return text[m.start():i + 1]
        raise SystemExit(f"export_figures: unbalanced parens in diagram of {source}")
    raise SystemExit(f"export_figures: no #diagram / #lq.diagram found in {source}")


def find_source(filename: str) -> Path:
    matches = sorted(SEANCES_DIR.rglob(filename))
    if not matches:
        raise SystemExit(f"export_figures: source not found: {filename}")
    return matches[0]


def main() -> None:
    parser = argparse.ArgumentParser(description="Export Typst diagrams to SVG.")
    parser.add_argument("--outdir", default=str(ROOT / "public" / "assets" / "figs"))
    parser.add_argument("--workdir", default=str(ROOT / ".build" / "figs"))
    parser.add_argument("--keep-wrappers", action="store_true",
                        help="Keep generated .typ wrappers (default: temp dir, removed).")
    args = parser.parse_args()

    typst = shutil.which("typst")
    if typst is None:
        raise SystemExit("export_figures: typst binary not found in PATH")

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    if args.keep_wrappers:
        workdir = Path(args.workdir)
        workdir.mkdir(parents=True, exist_ok=True)
        cleanup = None
    else:
        cleanup = tempfile.TemporaryDirectory(prefix="figs-", dir=str(ROOT))
        workdir = Path(cleanup.name)

    try:
        for filename, (stem, _alt, _caption) in FIGURE_SVGS.items():
            source = find_source(filename)
            diagram = extract_diagram(source)
            wrapper = workdir / f"{stem}.typ"
            wrapper.write_text(
                WRAPPER_TEMPLATE.format(source=source.relative_to(ROOT), diagram=diagram),
                encoding="utf-8",
            )
            dest = outdir / f"{stem}.svg"
            proc = subprocess.run(
                [typst, "compile", "--root", ".", "--format", "svg",
                 str(wrapper.relative_to(ROOT)), str(dest)],
                cwd=ROOT, capture_output=True, text=True,
            )
            if proc.returncode != 0:
                raise SystemExit(
                    f"export_figures: typst failed for {stem}:\n{proc.stderr.strip()}"
                )
            print(f"Figure exportée : {dest.relative_to(ROOT)}")
    finally:
        if cleanup is not None:
            cleanup.cleanup()


if __name__ == "__main__":
    main()
