#!/usr/bin/env python3
"""Export Typst diagrams to SVG for the website.

Stdlib only. Extracts all #diagram / #lq.diagram calls from each known
séance source in textual order (balanced parens, same technique as
build_site.py), wraps each in a page-auto document importing /template.typ,
and compiles it with ``typst compile --root . --format svg`` to
public/assets/figs/<stem>.svg.

Wrappers live in .build/figs/ (gitignored, never the repo), so a séance
edit is picked up on the next build with no manual wrapper sync. The
stem map (filenames, alt texts, captions) stays the single source of
truth in scripts/build_site.py:FIGURE_SVGS and is imported here.

Usage:
    python3 scripts/export_figures.py
    python3 scripts/export_figures.py --outdir public/assets/figs --workdir .build/figs
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import NamedTuple

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from build_site import FIGURE_SVGS  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SEANCES_DIR = ROOT / "seances"

# Match both the fletcher and lilaq diagram entry points.
DIAGRAM_RE = re.compile(r"#(?:lq\.)?diagram\s*\(")

WRAPPER_TEMPLATE = """\
// Generated by scripts/export_figures.py — do not edit.
// Source: {source}
#import "/template.typ": *

#set page(width: auto, height: auto, margin: 8pt)

#align(center)[
{diagram}
]
"""


def extract_diagrams(source: Path) -> list[str]:
    """Return every #diagram / #lq.diagram call in textual order."""
    text = source.read_text(encoding="utf-8")
    diagrams: list[str] = []
    for match in DIAGRAM_RE.finditer(text):
        open_idx = text.index("(", match.start(), match.end())
        depth = 0
        for index in range(open_idx, len(text)):
            if text[index] == "(":
                depth += 1
            elif text[index] == ")":
                depth -= 1
                if depth == 0:
                    diagrams.append(text[match.start():index + 1])
                    break
        else:
            raise SystemExit(
                f"export_figures: unbalanced parens in diagram of {source}"
            )
    if not diagrams:
        raise SystemExit(
            f"export_figures: no #diagram / #lq.diagram found in {source}"
        )
    return diagrams


def find_source(filename: str) -> Path:
    matches = sorted(SEANCES_DIR.rglob(filename))
    if not matches:
        raise SystemExit(f"export_figures: source not found: {filename}")
    return matches[0]


class FigureJob(NamedTuple):
    source: Path
    stem: str
    alt: str
    caption: str | None
    diagram: str


def figure_jobs() -> list[FigureJob]:
    jobs: list[FigureJob] = []
    for filename, entries in FIGURE_SVGS.items():
        source = find_source(filename)
        diagrams = extract_diagrams(source)
        if len(diagrams) != len(entries):
            raise SystemExit(
                "export_figures: "
                f"{filename} has {len(diagrams)} diagram occurrences "
                f"but {len(entries)} registry entries"
            )
        jobs.extend(
            FigureJob(source, stem, alt, caption, diagram)
            for (stem, alt, caption), diagram in zip(entries, diagrams)
        )
    return jobs


def main() -> None:
    parser = argparse.ArgumentParser(description="Export Typst diagrams to SVG.")
    parser.add_argument("--outdir", default=str(ROOT / "public" / "assets" / "figs"))
    parser.add_argument("--workdir", default=str(ROOT / ".build" / "figs"))
    parser.add_argument("--keep-wrappers", action="store_true",
                        help="Keep generated .typ wrappers (default: temp dir, removed).")
    args = parser.parse_args()

    typst = shutil.which("typst")
    if typst is None:
        raise SystemExit("export_figures: typst binary not found in PATH")

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    if args.keep_wrappers:
        workdir = Path(args.workdir)
        workdir.mkdir(parents=True, exist_ok=True)
        cleanup = None
    else:
        cleanup = tempfile.TemporaryDirectory(prefix="figs-", dir=str(ROOT))
        workdir = Path(cleanup.name)

    try:
        for job in figure_jobs():
            stem = job.stem
            wrapper = workdir / f"{stem}.typ"
            wrapper.write_text(
                WRAPPER_TEMPLATE.format(
                    source=job.source.relative_to(ROOT),
                    diagram=job.diagram,
                ),
                encoding="utf-8",
            )
            dest = outdir / f"{stem}.svg"
            proc = subprocess.run(
                [typst, "compile", "--root", ".", "--format", "svg",
                 str(wrapper.relative_to(ROOT)), str(dest)],
                cwd=ROOT,
                capture_output=True,
                text=True,
            )
            if proc.returncode != 0:
                raise SystemExit(
                    f"export_figures: typst failed for {stem}:\n"
                    f"{proc.stderr.strip()}"
                )
            try:
                display_dest = dest.relative_to(ROOT)
            except ValueError:
                display_dest = dest
            print(f"Figure exportée : {display_dest}")
    finally:
        if cleanup is not None:
            cleanup.cleanup()


if __name__ == "__main__":
    main()
